name: CI
on: [push, pull_request]

jobs:
    ci:
        strategy:
            fail-fast: false
            matrix:
                python-version: ["3.10.6"]
                poetry-version: ["1.7.1"]
                os: [ubuntu-20.04, macos-latest]

        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v2

            - uses: actions/setup-python@v2
              with:
                  python-version: ${{ matrix.python-version }}

            - name: Run image
              uses: abatilo/actions-poetry@v2.0.0
              with:
                  poetry-version: ${{ matrix.poetry-version }}

            - name: Install Dependencies
              run: |
                  poetry config virtualenvs.create false \
                    && poetry install --with dev --no-interaction

            - name: Run Tests (Python)
              run: make test

            - name: Lint (Python)
              run: make lint

            - name: Check Formatting (Python)
              run: make format
